export const RAPID_SCAN = 'RAPID'
export const INTELLIGENT_SCAN = 'INTELLIGENT'

export enum DetectEnvironmentProperties {
  NODE_TLS_REJECT_UNAUTHORIZED = 'NODE_TLS_REJECT_UNAUTHORIZED',
  DETECT_DIAGNOSTIC = 'DETECT_DIAGNOSTIC',
  DETECT_DIAGNOSTIC_EXTENDED = 'DETECT_DIAGNOSTIC_EXTENDED'
}

// noinspection SpellCheckingInspection
export const RUNNER_DEFAULT_OUTPUT_DIRECTORY = 'blackduck'
